### ISSUE TITLE
Detailansicht Veranstaltung - Learning Outcomes

### ISSUE THREAD

**Issue by vschaefer** [fh-koeln/LevelPad#28]
- [ ] **F2801** Zu jedem Learning Outcome wird die Bezeichnung und die Gewichtung als prozentualer Anteil von der Gesamtnote angezeigt.
- [ ] [2] **F2802** Die Gewichtung soll in einem Tortendiagramm dargestellt werden, dass sich proportional zu dem prozentualen Anteil füllt.
- [ ] **F2803** Wird die Schaltfläche "neues Learning Outcome hinzufügen" ausgewählt wird die Dialogbox #29 angezeigt.
- [ ] [3] **F2804** Wird die Schaltfläche "Learning Outcomes importieren" ausgewählt wird die Dialogbox #30 angezeigt.
- [ ] **F2805** Wird ein Learning Outcome ausgewählt, soll die Detailansicht zu dem ausgewählten Learning Outcome #31 angezeigt werden.
