### ISSUE TITLE
Learning Outcome - Detailansicht

### ISSUE THREAD

**Issue by vschaefer** [fh-koeln/LevelPad#31]
- [ ] **F3101** Neben der Bezeichnung des Learning Outcomes sollen die Beschreibung und die prozentuale Gewichtung angezeigt werden.
- [ ] [2] **F3102** Die prozentuale Gewichtung soll in einem Tortendiagramm visualisiert werden. Das Tortendiagramm soll sich proportional zu der angegeben Gewichtung füllen.
- [ ] **F3103** Zu dem Learning Outcome sollen die Beschreibungen der Niveaustufen in hierarchischer Reihenfolge (Beste zuerst, schlechteste zuletzt) angezeigt werden.
- [ ] [2]  **F3104** Über den "Anfasser" soll eine Niveaustufe über Drag & Drop in der Hierarchie verschoben werden können.
- [ ] **F3105** Die Balken, in der die Bezeichnungen der Niveaustufen stehen, sollen nach folgender Vorschrift gefärbt werden: grün = ausreichende Niveaustufe, rot = nicht ausreichende Niveaustufe.
- [ ] **F3106** Wird das Icon neben der Bezeichnung des Learning Outcomes ausgewählt, soll die Dialogbox zum Bearbeiten des Learning Outcomes #32 angezeigt werden.
- [ ] **F3107** Wird eine Niveaustufe ausgewählt, sollen die Details zu dieser Niveaustufe #33 angezeigt werden. Bei erneuter Auswahl, sollen die Details wieder ausgeblendet werden.
- [ ] **F3108** Wird die Schaltfläche "Niveaustufe hinzufügen" ausgewählt wird das Dialogfenster #34 angezeigt.
