### ISSUE TITLE
ToDo 8.12.14

### ISSUE THREAD

**Issue by medariox** [fh-koeln/LevelPad#42]
-  [x] Dialog anpassen http://127.0.0.1:5000/users
-  [x] Admin/Assistenten und Studenten Link http://127.0.0.1:5000/
-  [x] GET für /api/modules/ und /api/modules/XXX/subject für Studenten erlauben => /api/subjects/ reaktivieren
-  [x] Authentifizierung/Zugriffsberechtigung für Routen
-  [x] Richtige Kalkulierung der Gewichtungen
-  [x] Höhe der Zeilen für Niveaustufen anpassen
-  [x] Dialog für Niveaustufenbearbeitung
