### ISSUE TITLE
ToDo: 10.12.14

### ISSUE THREAD

**Issue by ocean90** [fh-koeln/LevelPad#44]
- [x] Notenberechnung implementieren @BenWur 
- [x] Overlay für Niveaustufen pro LO (http://localhost:5000/ma1/wise1617/members/xxxxx) @BenWur 
- [x] API: Ausgabe filtern, /api/subjects/ sollte zB keine Passwörter zeigen @dvizzacc 
- [ ] Breadcrumb Navigation @jerolimov 
- [ ] AlertService: Fehlermeldung vor Routenwechsel registrieren, welche **nicht** gelöscht werden @jerolimov 
- [x] Modules: An neue Syntax für Dialoge anpassen @ocean90
- [x] Direktive für rollenspezifische Elemente
