### ISSUE TITLE
ToDo: 15.12.14

### ISSUE THREAD

**Issue by ocean90** [fh-koeln/LevelPad#45]
- [x] Veranstaltung joinen @dvizzacc 
- [x] Overlay für Niveaustufen @BenWur
- [x] Neues Learning Outcome postive/negativ ohne Rahmen @BenWur 
- [x] Member-Ansicht Padding/Margin überprüfen @dvizzacc 
- [x] API: Ausgabe filtern, /api/users/$user/subjects/ sollte zB keine Passwörter zeigen @dvizzacc
- [x] tbc
