### ISSUE TITLE
ToDo: 17.12.14

### ISSUE THREAD

**Issue by BenWur** [fh-koeln/LevelPad#46]
- [x] Noten und Artefakte in Listenansicht
- [x] ACL @ocean90
- [ ] Datensätze kaskadierend löschen @dvizzacc 
- [ ] siehe ToDos vom #44 @jerolimov 
- [x] Sortierung von Niveaustufen überprüfen @BenWur
